### ISSUE TITLE
Add new project maintainers

### ISSUE THREAD

**Issue by quaid** [open-infrastructure-labs/openinfralabs-website#12]
We don't have a governance yet, but a small group of us are working on the first draft. As part of that work, we will need to make changes to the website.

@durandom It looks like just your team have perms here, can you add:

* @msdisme
* @quaid 
* @juliakreger

**Comment by juliakreger** [comment]
Sure!

**Comment by msdisme** [comment]
I added quaid via teams and julia via owner role mostly so that we can figure out if teams worked the way it was intended, and so that Julia can fix quaid's access in case I am not about.
