### ISSUE TITLE
Missing logos from Supporting Organizations

### ISSUE THREAD

**Issue by msdisme** [open-infrastructure-labs/openinfralabs-website#2]
This page, https://openinfralabs.org/supporters/, is missing some logos which got added to old design and included University of Ohio and Columbia.

**Comment by jimmytipit** [comment]
Can someone send to jimmy@openstack.org the missing logos that need to be added?  Happy to do it.

**Comment by msdisme** [comment]
I am double checking on Columbia.

I think that there are two UMass ones there now.   Also please add Stony Brook and Ohio State who are participating in caerus/wenju stuff.

The links are https://www.stonybrook.edu/sbu-brand/design-visual-identity/logos   ,  https://www.umassp.edu/communications/brand-guidelines/look-and-feel   , and https://brand.osu.edu/logo/

(Corrected Umass link to be for general UMass)

**Comment by msdisme** [comment]
OSU: https://github.com/open-infrastructure-labs/openinfralabs-website/blob/master/static/img/sponsors/TheOhioStateUniversity-Stacked.png

**Comment by jimmytipit** [comment]
This is set to go: https://openinfralabs.org/supporters/

Cheers!

**Comment by msdisme** [comment]
@jimmytipit I just realized I made a mistake, the second one which said Massachusetts was the state seal and does belong there :-(.

**Comment by jimmytipit** [comment]
NP - just added back in.  Should show momentarily.
